name: C++ Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Quick Sort
        run: g++ -std=c++17 -Wall -Wextra main.cpp -o quicksort

      - name: Run Quick Sort
        run: ./quicksort
